require 'rake/testtask'
require 'rubygems/tasks'
require 'rubygems/package_task'

Rake::TestTask.new do |t|
  t.libs << 'test'
end

Gem::Tasks.new do |tasks|
  tasks.console.command = 'jruby'
end

desc "Run tests"
task :default => :test